version: "3.8"

services:
  api_1:
    build:
      context: ./api_1
    ports:
      - "4000:8000"
    restart: always

  api_2:
    build:
      context: ./api_2
    ports:
      - "4001:4000"
    restart: always

  web:
    build:
      context: ./web
    ports:
      - "3000:80"
    restart: always