# Etapa 1: Build da aplicação ReactJS
FROM node:22 AS builder

# Diretório de trabalho dentro do container
WORKDIR /app

# Copiar package.json e package-lock.json para o container
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar os arquivos do projeto para o container
COPY . .

# Construir a aplicação para produção
RUN npm run build

# Etapa 2: Configuração do servidor Nginx
FROM nginx:alpine

# Copiar os arquivos buildados da etapa anterior para o diretório do nginx
COPY --from=builder /app/build /usr/share/nginx/html

# Copiar o arquivo de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expor a porta padrão do Nginx
EXPOSE 80

# Iniciar o servidor Nginx
CMD ["nginx", "-g", "daemon off;"]